import 'package:efiling_balochistan/config/router/route_helper.dart';
import 'package:efiling_balochistan/constants/app_colors.dart';
import 'package:efiling_balochistan/controllers/controllers.dart';
import 'package:efiling_balochistan/models/file_details_model.dart';
import 'package:efiling_balochistan/models/file_model.dart';
import 'package:efiling_balochistan/models/flag_model.dart';
import 'package:efiling_balochistan/models/forward_to.dart';
import 'package:efiling_balochistan/models/new_file_data_model.dart';
import 'package:efiling_balochistan/models/section_schema.dart';
import 'package:efiling_balochistan/services/ai_agent.dart';
import 'package:efiling_balochistan/utils/validators.dart';
import 'package:efiling_balochistan/views/screens/base_screen/base_screen.dart';
import 'package:efiling_balochistan/views/screens/chats/ai_agent_chat_screen.dart';
import 'package:efiling_balochistan/views/screens/files/flag_attachement/add_file_flag_and_attachmention.dart';
import 'package:efiling_balochistan/views/screens/files/preview_file.dart';
import 'package:efiling_balochistan/views/widgets/app_text.dart';
import 'package:efiling_balochistan/views/widgets/buttons/outline_button.dart';
import 'package:efiling_balochistan/views/widgets/buttons/solid_button.dart';
import 'package:efiling_balochistan/views/widgets/text_fields/app_drop_down_field.dart';
import 'package:efiling_balochistan/views/widgets/text_fields/app_text_field.dart';
import 'package:efiling_balochistan/views/widgets/toast.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:quill_html_editor_v2/quill_html_editor_v2.dart';

class CreateNewFileScreen extends ConsumerStatefulWidget {
  const CreateNewFileScreen({super.key});

  @override
  ConsumerState<CreateNewFileScreen> createState() =>
      _CreateNewFileScreenState();
}

class _CreateNewFileScreenState extends ConsumerState<CreateNewFileScreen> {
  final GlobalKey<FormState> formKey = GlobalKey<FormState>();
  final TextEditingController fileNo = TextEditingController();
  final TextEditingController partFileNo = TextEditingController();
  final TextEditingController fileMovementNo = TextEditingController();
  final TextEditingController subject = TextEditingController();

  final QuillEditorController quillEditorController = QuillEditorController();
  bool showHtmlEditor = true;

  bool loading = true;
  String autoGeneratedFileNumber = '';
  List<FlagModel> allFlags = [];
  List<FileTypeModel> fileTypes = [];
  List<TagModel> tags = [];
  List<ForwardToModel>? forwardToList;
  SectionModel? selectedSection;
  ForwardToModel? forwardTo;
  FileTypeModel? selectedFileType;
  TagModel? selectedTag;

  List<FlagAndAttachmentModel> attachments = [
    FlagAndAttachmentModel(),
  ];

  bool get allAttachmentsValid => attachments.every((e) => e.isValid);

  Future fetchData() async {
    final controller = ref.read(filesController.notifier);
    controller.getSections();
    NewFileDataModel? data = await controller.getFileData();
    fileTypes = data?.fileTypes ?? [];
    tags = data?.tags ?? [];
    allFlags = await controller.getFlags();
    autoGeneratedFileNumber = await controller.autoGenerateFileMovNumber();
    fileMovementNo.text = autoGeneratedFileNumber;
    setState(() {
      loading = false;
    });
  }

  @override
  void initState() {
    AIAgent().resetMessages();
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      // final delta = {
      //   "ops": [
      //     {"insert": "\u00A0\u00A0\u00A0"} // three nbsp
      //   ]
      // };
      // await quillEditorController.setDelta(delta);

      fetchData();
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(filesController);
    return BaseScreen(
      title: "Create New File",
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16),
          child: Form(
            key: formKey,
            child: Column(
              children: [
                header(Icons.text_snippet_outlined, "File Details"),
                const SizedBox(height: 16),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      child: AppDropDownField<FileTypeModel>(
                        items: fileTypes,
                        onChanged: (item) {
                          setState(() {
                            selectedFileType = item;
                          });
                        },
                        labelText: "File Type",
                        hintText: "Select file type",
                        prefix: state.loadingNewFileData ? fieldLoader : null,
                        itemBuilder: (item) {
                          return AppText.titleMedium(item?.title ?? '');
                        },
                        validator: (item) {
                          if (selectedFileType == null || item == null) {
                            return 'Please select a file type';
                          }
                          return null;
                        },
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: AppDropDownField<TagModel>(
                        items: tags,
                        onChanged: (item) {
                          setState(() {
                            selectedTag = item;
                          });
                        },
                        labelText: "Tag",
                        hintText: "Select tag",
                        itemBuilder: (item) {
                          return AppText.titleMedium(item?.title ?? '');
                        },
                        prefix: state.loadingNewFileData ? fieldLoader : null,
                        validator: (item) {
                          if (selectedTag == null || item == null) {
                            return 'Please select a tag';
                          }
                          return null;
                        },
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      child: AppTextField(
                        controller: fileNo,
                        labelText: "File No",
                        hintText: "Enter file number",
                        validator: Validators.notEmptyValidator,
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      child: AppTextField(
                        controller: partFileNo,
                        labelText: "Part File No",
                        hintText: "Enter if any",
                        //validator: Validators.notEmptyValidator,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 12),
                AppTextField(
                  controller: subject,
                  labelText: "File Subject",
                  hintText: "Enter subject",
                  validator: Validators.notEmptyValidator,
                ),
                const SizedBox(height: 12),
                Align(
                  alignment: Alignment.centerLeft,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      AppText.titleLarge(
                        "Autogenerated File Number is:",
                        color: AppColors.secondaryDark,
                      ),
                      AppText.bodyMedium(autoGeneratedFileNumber),
                    ],
                  ),
                ),
                const SizedBox(height: 16),
                header(Icons.description_outlined, "File Description"),
                const SizedBox(height: 16),
                ClipRRect(
                  borderRadius: BorderRadius.circular(12),
                  child: Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                        border: Border.all(
                            color: AppColors.secondaryLight.withOpacity(0.5)),
                        borderRadius: BorderRadius.circular(12),
                        color: AppColors.white),
                    child: Column(
                      children: [
                        ToolBar(
                          activeIconColor: Colors.blue,
                          padding: const EdgeInsets.all(8),
                          iconSize: 24,
                          controller: quillEditorController,
                          toolBarConfig: const [
                            ToolBarStyle.bold,
                            ToolBarStyle.italic,
                            ToolBarStyle.underline,
                            //ToolBarStyle.listBullet,
                            ToolBarStyle.listOrdered,
                            ToolBarStyle.size,
                            ToolBarStyle.headerOne,
                            ToolBarStyle.headerTwo,
                            ToolBarStyle.link,
                            ToolBarStyle.align,
                            ToolBarStyle.color,
                            ToolBarStyle.blockQuote,
                            ToolBarStyle.codeBlock,
                            ToolBarStyle.addTable,
                            ToolBarStyle.editTable,
                          ],
                        ),
                        Divider(color: Colors.grey[300]!),
                        const SizedBox(height: 8),
                        Container(
                          child: showHtmlEditor
                              ? QuillHtmlEditor(
                                  text: '',
                                  hintText: "...",
                                  autoFocus: true,
                                  controller: quillEditorController,
                                  minHeight: 270,
                                  textStyle: const TextStyle(
                                    fontSize: 16,
                                    color: Colors.black,
                                  ),
                                  hintTextStyle: const TextStyle(
                                    fontSize: 16,
                                    color: Colors.grey,
                                  ),
                                  onEditorCreated: () {
                                    quillEditorController.requestFocus();
                                  },
                                )
                              : const SizedBox.shrink(),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 12),
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    // AppOutlineButton(
                    //   onPressed: () {
                    //     RouteHelper.push(Routes.fileChat(0));
                    //   },
                    //   text: "Start Discussion",
                    //   icon: Icons.chat,
                    //   color: AppColors.primaryDark,
                    //   textSize: 16,
                    //   padding: const EdgeInsets.symmetric(
                    //       horizontal: 16, vertical: 12),
                    // ),
                    // const SizedBox(width: 12),
                    AppOutlineButton(
                      onPressed: () {
                        showModalBottomSheet(
                          context: context,
                          constraints: BoxConstraints(
                              maxHeight:
                                  MediaQuery.sizeOf(context).height * 0.9),
                          showDragHandle: false,
                          isScrollControlled: true,
                          backgroundColor: AppColors.background,
                          shape: const RoundedRectangleBorder(
                            borderRadius: BorderRadius.only(
                              topLeft: Radius.circular(16),
                              topRight: Radius.circular(16),
                            ),
                          ),
                          builder: (BuildContext context) {
                            return const Padding(
                              padding: EdgeInsets.fromLTRB(8, 8, 8, 0),
                              child: AIAgentChatScreen(generateNew: true),
                            );
                          },
                        ).then((text) {
                          if (text != null) {
                            quillEditorController.setText(text);
                          }
                        });
                      },
                      text: "Draft with AI",
                      icon: Icons.drafts_rounded,
                      color: AppColors.secondary,
                      padding: const EdgeInsets.symmetric(
                          horizontal: 16, vertical: 12),
                    ),
                  ],
                ),
                const SizedBox(height: 24),
                Column(
                  children: [
                    header(Icons.work_history_outlined, "Section"),
                    const SizedBox(height: 16),
                    AppDropDownField<SectionModel>(
                      items: state.sections,
                      onChanged: (item) async {
                        setState(() {
                          selectedSection = item;
                        });
                        forwardToList = await ref
                            .read(filesController.notifier)
                            .getForwardTo(item?.id);
                        setState(() {
                          if (forwardToList != null &&
                              forwardToList?.length == 1) {
                            forwardTo = forwardToList?.first;
                          }
                        });
                      },
                      labelText: "Section",
                      hintText: "Select Section",
                      prefix: state.loadingSections ? fieldLoader : null,
                      itemBuilder: (item) {
                        return AppText.titleMedium(item?.title ?? '');
                      },
                      validator: (item) {
                        if (selectedSection == null || item == null) {
                          return 'Please select a value';
                        }
                        return null;
                      },
                    ),
                    const SizedBox(height: 12),
                    AppDropDownField<ForwardToModel>(
                      items: forwardToList ?? [],
                      onChanged: (item) async {
                        setState(() {
                          forwardTo = item;
                        });
                      },
                      labelText: "Forward this file to",
                      hintText: "Forward To",
                      buttonHeight: 40,
                      prefix: state.loadingSections ? fieldLoader : null,
                      itemBuilder: (item) {
                        return Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            AppText.titleSmall(item?.userTitle ?? ''),
                            AppText.labelLarge(item?.designationTitle ?? ''),
                          ],
                        );
                      },
                      selectedItemBuilder: (ctx) {
                        return forwardToList?.map((item) {
                              return SizedBox(
                                height: 48, // 👈 adjust so both lines fit
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    AppText.titleSmall(item.userTitle ?? ''),
                                    AppText.labelLarge(
                                        item.designationTitle ?? ''),
                                  ],
                                ),
                              );
                            }).toList() ??
                            [];
                      },
                      validator: (item) {
                        if (forwardTo == null || item == null) {
                          return 'Please select a value';
                        }
                        return null;
                      },
                    ),
                  ],
                ),
                const SizedBox(height: 16),
                header(Icons.flag_outlined, "Flag & Attachment"),
                const SizedBox(height: 16),
                ListView.separated(
                  itemCount: attachments.length,
                  shrinkWrap: true,
                  physics: const NeverScrollableScrollPhysics(),
                  separatorBuilder: (_, i) => Divider(
                    height: 40,
                    color: AppColors.secondaryLight.withOpacity(0.5),
                  ),
                  itemBuilder: (ctx, i) {
                    final model = attachments[i];
                    return AddFlagAndAttachment(
                      key: ValueKey(
                          model), // keep identity stable across rebuilds
                      model: model,
                      onDelete: () {
                        setState(() => attachments.removeAt(i));
                      },
                    );
                  },
                ),
                const SizedBox(height: 12),
                Align(
                  alignment: Alignment.centerRight,
                  child: AppOutlineButton(
                    onPressed: () {
                      setState(() {
                        attachments.add(FlagAndAttachmentModel());
                      });
                    },
                    text: "Add More",
                    color: AppColors.secondary,
                    padding: const EdgeInsets.symmetric(
                        horizontal: 16, vertical: 12),
                  ),
                ),
                const SizedBox(height: 40),
                Row(
                  children: [
                    Container(
                      height: 50,
                      width: 150,
                      child: AppSolidButton(
                          onPressed: () async {
                            final String desc =
                                await quillEditorController.getText();
                            final user = ref.read(authController);
                            if (!context.mounted) return;
                            showModalBottomSheet(
                              context: context,
                              constraints: BoxConstraints(
                                  maxHeight:
                                      MediaQuery.sizeOf(context).height * 0.9),
                              showDragHandle: false,
                              isScrollControlled: true,
                              backgroundColor: AppColors.background,
                              shape: const RoundedRectangleBorder(
                                borderRadius: BorderRadius.only(
                                  topLeft: Radius.circular(16),
                                  topRight: Radius.circular(16),
                                ),
                              ),
                              builder: (BuildContext context) {
                                return SingleChildScrollView(
                                  padding: const EdgeInsets.all(16),
                                  child: Column(
                                    children: [
                                      Row(
                                        children: [
                                          Expanded(
                                            child: AppText.headlineSmall(
                                              "File Preview",
                                            ),
                                          ),
                                          IconButton(
                                            onPressed: () {
                                              RouteHelper.pop();
                                            },
                                            icon: const Icon(
                                              Icons.close,
                                              color: AppColors.textPrimary,
                                            ),
                                          ),
                                        ],
                                      ),
                                      PreviewFile(
                                        content: [
                                          FileContentModel(
                                            subject: subject.text,
                                            fileType:
                                                selectedFileType?.title ?? '',
                                            barcode: autoGeneratedFileNumber,
                                            content: desc,
                                            fileMovNo: autoGeneratedFileNumber,
                                            sender: user.userTitle,
                                            designation: user.currentDesignation
                                                ?.designation,
                                            signature: user.sign,
                                            sendingDate: DateTime.now(),
                                            receiver: forwardTo?.userTitle,
                                          )
                                        ],
                                      ),
                                      const SizedBox(height: 16),
                                      AppOutlineButton(
                                        onPressed: () {
                                          RouteHelper.pop();
                                        },
                                        text: "Close",
                                        color: AppColors.primaryDark,
                                        width: double.infinity,
                                        padding: const EdgeInsets.symmetric(
                                            horizontal: 16, vertical: 12),
                                      ),
                                    ],
                                  ),
                                );
                              },
                            );
                          },
                          text: "Preview"),
                    ),
                    const SizedBox(width: 16),
                    Container(
                      height: 50,
                      width: 150,
                      child: AppSolidButton(
                        onPressed: () async {
                          if (!formKey.currentState!.validate()) return;
                          String text = await quillEditorController.getText();
                          if (text.trim().isEmpty) {
                            Toast.show(
                                message: "Add remarks before you submit");
                            return;
                          }
                          if (!allAttachmentsValid) {
                            Toast.error(
                                message:
                                    "One or more flags are missing attachments. Add a file and then try again");
                            return;
                          }
                          final controller = ref.read(filesController.notifier);
                          controller.createFile(
                            subject: subject.text,
                            fileType: selectedFileType?.id,
                            content: text,
                            forwardTo: forwardTo?.userDesgId,
                            fileMovNumber: autoGeneratedFileNumber,
                            fileNo: fileNo.text,
                            partFileNumber: partFileNo.text,
                            tagId: selectedTag?.id,
                            flags: attachments,
                          );

                          //RouteHelper.navigateTo(Routes.dashboard);
                        },
                        text: "Submit",
                        backgroundColor: AppColors.secondary,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 16),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget header(IconData icon, String title) {
    return Row(
      children: [
        Card(
          margin: const EdgeInsets.all(0),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
          color: AppColors.cardColor,
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Icon(icon, size: 24, color: AppColors.primaryDark),
          ),
        ),
        const SizedBox(width: 8),
        AppText.headlineSmall(
          title,
          color: AppColors.primaryDark,
        ),
      ],
    );
  }

  final Widget fieldLoader = Container(
    width: 12,
    height: 12,
    margin: const EdgeInsets.only(right: 8),
    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 12),
    child: const CircularProgressIndicator(
      strokeWidth: 2,
    ),
  );
}
