import 'package:efiling_balochistan/config/router/route_helper.dart';
import 'package:efiling_balochistan/config/router/routes.dart';
import 'package:efiling_balochistan/constants/app_colors.dart';
import 'package:efiling_balochistan/controllers/controllers.dart';
import 'package:efiling_balochistan/models/file_details_model.dart';
import 'package:efiling_balochistan/models/flag_model.dart';
import 'package:efiling_balochistan/models/forward_to.dart';
import 'package:efiling_balochistan/models/section_schema.dart';
import 'package:efiling_balochistan/services/ai_agent.dart';
import 'package:efiling_balochistan/views/screens/chats/ai_agent_chat_screen.dart';
import 'package:efiling_balochistan/views/screens/files/file_card.dart';
import 'package:efiling_balochistan/views/screens/files/flag_attachement/add_file_flag_and_attachmention.dart';
import 'package:efiling_balochistan/views/screens/files/flag_attachement/read_only_flag_attachment.dart';
import 'package:efiling_balochistan/views/screens/files/preview_file.dart';
import 'package:efiling_balochistan/views/screens/sticky_tag_drawer.dart';
import 'package:efiling_balochistan/views/widgets/app_text.dart';
import 'package:efiling_balochistan/views/widgets/buttons/outline_button.dart';
import 'package:efiling_balochistan/views/widgets/buttons/shimmer_button.dart';
import 'package:efiling_balochistan/views/widgets/buttons/solid_button.dart';
import 'package:efiling_balochistan/views/widgets/chips/selection_chips.dart';
import 'package:efiling_balochistan/views/widgets/loading_card.dart';
import 'package:efiling_balochistan/views/widgets/text_fields/app_drop_down_field.dart';
import 'package:efiling_balochistan/views/widgets/toast.dart';
import 'package:flutter/material.dart';
import 'package:flutter_animate/flutter_animate.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:quill_html_editor_v2/quill_html_editor_v2.dart';

enum FileAction {
  approved(1, "Approved"),
  notApproved(2, "Not Approved"),
  forward(3, "Forward");

  final int value;
  final String label;
  const FileAction(this.value, this.label);
}

class FileDetailsScreen extends ConsumerStatefulWidget {
  final int? fileId;
  final FileType fileType;
  const FileDetailsScreen({
    super.key,
    required this.fileId,
    required this.fileType,
  });

  @override
  ConsumerState<FileDetailsScreen> createState() => _FileDetailsScreenState();
}

class _FileDetailsScreenState extends ConsumerState<FileDetailsScreen> {
  final GlobalKey<FormState> formKey = GlobalKey<FormState>();
  final ScrollController scrollController = ScrollController();
  final GlobalKey remarksKey = GlobalKey();

  final quillEditorController = QuillEditorController();
  String? selectedFileType;
  bool showHtmlEditor = true;
  bool loading = true;
  String autoGeneratedFileNumber = '';
  FileDetailsModel? details;
  List<FlagModel> allFlags = [];
  List<ForwardToModel>? forwardToList;
  SectionModel? selectedSection;
  ForwardToModel? forwardTo;
  FileAction action = FileAction.approved;
  bool reOpenedFile = false;

  List<FlagAndAttachmentModel> attachments = [
    FlagAndAttachmentModel(),
  ];

  List<FlagModel> get flagsUsed =>
      details?.attachments == null || details!.attachments.isEmpty
          ? []
          : details!.attachments
              .map((a) => allFlags.firstWhere(
                    (e) =>
                        e.title == a.flagTitle &&
                        e.title?.toLowerCase() != 'final attachment',
                    orElse: () => FlagModel(),
                  ))
              .where((f) => f.id != null)
              .toList();

  bool get allAttachmentsValid => attachments.every((e) => e.isValid);

  bool get viewOnly =>
      widget.fileType == FileType.my ||
      widget.fileType == FileType.forwarded ||
      isUnopenedArchived;

  bool get isUnopenedArchived =>
      widget.fileType == FileType.archived && reOpenedFile == false;

  scrollToRemarks() {
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final context = remarksKey.currentContext;
      if (context != null) {
        Scrollable.ensureVisible(
          context,
          duration: const Duration(milliseconds: 300),
          curve: Curves.easeInOut,
        );
      }
    });
  }

  initAttachment() {
    if (widget.fileType == FileType.actionRequired &&
        action != FileAction.forward) {
      attachments = [
        FlagAndAttachmentModel(usedFlags: []),
      ];
    } else {
      attachments = [
        FlagAndAttachmentModel(
          usedFlags: [
            ...flagsUsed,
            ...attachments.map((e) => e.flagType ?? FlagModel()).toList() ?? [],
          ],
        ),
      ];
    }
  }

  Future fetchData() async {
    final controller = ref.read(filesController.notifier);
    if (viewOnly) {
      details =
          await controller.fetchFileDetails(widget.fileId!, widget.fileType);
      setState(() {
        loading = false;
      });
      return;
    }
    controller.getSections();
    allFlags = await controller.getFlags(
        onlyFinal: widget.fileType == FileType.actionRequired);
    details =
        await controller.fetchFileDetails(widget.fileId!, widget.fileType);
    autoGeneratedFileNumber = await controller.autoGenerateFileMovNumber();
    initAttachment();
    setState(() {
      loading = false;
    });
  }

  @override
  void initState() {
    AIAgent().resetMessages();
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      final delta = {
        "ops": [
          {"insert": "\u00A0\u00A0\u00A0"} // three nbsp
        ]
      };
      await quillEditorController.setDelta(delta);

      fetchData();
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    final state = ref.watch(filesController);
    final controller = ref.read(filesController.notifier);
    return RefreshIndicator(
      onRefresh: fetchData,
      child: Scaffold(
        appBar: AppBar(
          title: AppText.headlineSmall("File Details"),
          backgroundColor: AppColors.background,
          centerTitle: false,
          actions: [
            if (details != null)
              Padding(
                padding: const EdgeInsets.symmetric(horizontal: 16.0),
                child: AppShimmerButton(
                  onPressed: () {
                    showModalBottomSheet(
                      context: context,
                      constraints: BoxConstraints(
                          maxHeight: MediaQuery.sizeOf(context).height * 0.9),
                      showDragHandle: false,
                      isScrollControlled: true,
                      backgroundColor: AppColors.background,
                      shape: const RoundedRectangleBorder(
                        borderRadius: BorderRadius.only(
                          topLeft: Radius.circular(16),
                          topRight: Radius.circular(16),
                        ),
                      ),
                      builder: (BuildContext context) {
                        return Padding(
                          padding: const EdgeInsets.fromLTRB(8, 8, 8, 0),
                          child: AIAgentChatScreen(
                            file: details,
                            suggestResponse: true,
                          ),
                        );
                      },
                    ).then((text) {
                      if (text != null) {
                        quillEditorController.setText(text);
                        scrollToRemarks();
                      }
                    });
                  },
                  text: "E-Filing Assistant",
                  icon: Icons.auto_awesome,
                  // color: AppColors.secondaryDark,
                  //backgroundColor: AppColors.secondaryDark,
                  fontSize: 16,
                  padding:
                      const EdgeInsets.symmetric(horizontal: 0, vertical: 4),
                ).animate().scale(
                      duration: 1200.ms,
                      begin: const Offset(0.97, 0.97),
                      end: const Offset(1.02, 1.02),
                      curve: Curves.easeInOut,
                    ),
              ),
          ],
        ),
        body: loading
            ? const Padding(
                padding: EdgeInsets.all(16.0),
                child: LoadingCard(),
              )
            : SafeArea(
                child: StickyTagDrawer(
                  flagText: "Flags",
                  panelWidth: MediaQuery.sizeOf(context).width * 0.8,
                  panelContent: SingleChildScrollView(
                    child: Container(
                      padding: const EdgeInsets.fromLTRB(16, 0, 16, 16),
                      child: details?.attachments != null &&
                              details!.attachments.isNotEmpty
                          ? ReadOnlyFlagAttachmentList(
                              header:
                                  header(Icons.flag_outlined, "Attached Flags"),
                              data: details!.attachments,
                            )
                              .animate(delay: 100.ms)
                              .fade(duration: 400.ms, curve: Curves.easeInOut)
                              .slide(
                                  begin: const Offset(1, 0), end: Offset.zero)
                          : Center(
                              child: AppText.bodyMedium("No flags available"),
                            ),
                    ),
                  ),
                  mainContent: SingleChildScrollView(
                    controller: scrollController,
                    padding: const EdgeInsets.all(16),
                    child: Form(
                      key: formKey,
                      child: Column(
                        children: [
                          header(Icons.text_snippet_outlined, "File"),
                          const SizedBox(height: 16),
                          PreviewFile(content: details?.content),
                          const SizedBox(height: 24),
                          if (!viewOnly)
                            Column(
                              key: remarksKey,
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                header(
                                    Icons.short_text_outlined, "Add Remarks"),
                                const SizedBox(height: 16),
                                ClipRRect(
                                  borderRadius: BorderRadius.circular(12),
                                  child: Container(
                                    padding: const EdgeInsets.all(8),
                                    decoration: BoxDecoration(
                                        border: Border.all(
                                            color: AppColors.secondaryLight
                                                .withOpacity(0.5)),
                                        borderRadius: BorderRadius.circular(12),
                                        color: AppColors.white),
                                    child: Column(
                                      children: [
                                        ToolBar(
                                          activeIconColor: Colors.blue,
                                          padding: const EdgeInsets.all(8),
                                          iconSize: 24,
                                          controller: quillEditorController,
                                          toolBarConfig: const [
                                            ToolBarStyle.bold,
                                            ToolBarStyle.italic,
                                            ToolBarStyle.underline,
                                            //ToolBarStyle.listBullet,
                                            ToolBarStyle.listOrdered,
                                            ToolBarStyle.size,
                                            ToolBarStyle.headerOne,
                                            ToolBarStyle.headerTwo,
                                            ToolBarStyle.link,
                                            ToolBarStyle.align,
                                            ToolBarStyle.color,
                                            ToolBarStyle.blockQuote,
                                            ToolBarStyle.codeBlock,
                                            ToolBarStyle.addTable,
                                            ToolBarStyle.editTable,
                                          ],
                                        ),
                                        Divider(color: Colors.grey[300]!),
                                        const SizedBox(height: 8),
                                        Container(
                                          child: showHtmlEditor
                                              ? GestureDetector(
                                                  onLongPress: () {},
                                                  onLongPressStart: (_) {},
                                                  onLongPressMoveUpdate: (_) {},
                                                  child: AbsorbPointer(
                                                    absorbing: false,
                                                    child: QuillHtmlEditor(
                                                      text: '',
                                                      hintText: "...",
                                                      autoFocus: true,
                                                      controller:
                                                          quillEditorController,
                                                      minHeight: 270,
                                                      textStyle:
                                                          const TextStyle(
                                                        fontSize: 16,
                                                        color: Colors.black,
                                                      ),
                                                      hintTextStyle:
                                                          const TextStyle(
                                                        fontSize: 16,
                                                        color: Colors.grey,
                                                      ),
                                                      onEditorCreated: () {
                                                        quillEditorController
                                                            .requestFocus();
                                                      },
                                                    ),
                                                  ),
                                                )
                                              : const SizedBox.shrink(),
                                        ),
                                      ],
                                    ),
                                  ),
                                ),
                                const SizedBox(height: 12),
                                Row(
                                  mainAxisAlignment: MainAxisAlignment.end,
                                  children: [
                                    if (details?.content != null)
                                      AppOutlineButton(
                                        onPressed: () {
                                          RouteHelper.push(
                                              Routes.fileChat(details!
                                                  .content.first.fileId),
                                              extra: details);
                                        },
                                        text: "Start Chat",
                                        icon: Icons.chat,
                                        color: AppColors.primaryDark,
                                        padding: const EdgeInsets.symmetric(
                                            horizontal: 16, vertical: 12),
                                      ),
                                    const SizedBox(width: 12),
                                    AppOutlineButton(
                                      onPressed: () {
                                        showModalBottomSheet(
                                          context: context,
                                          constraints: BoxConstraints(
                                              maxHeight:
                                                  MediaQuery.sizeOf(context)
                                                          .height *
                                                      0.9),
                                          showDragHandle: false,
                                          isScrollControlled: true,
                                          backgroundColor: AppColors.background,
                                          shape: const RoundedRectangleBorder(
                                            borderRadius: BorderRadius.only(
                                              topLeft: Radius.circular(16),
                                              topRight: Radius.circular(16),
                                            ),
                                          ),
                                          builder: (BuildContext context) {
                                            return Padding(
                                              padding:
                                                  const EdgeInsets.fromLTRB(
                                                      8, 8, 8, 0),
                                              child: AIAgentChatScreen(
                                                file: details,
                                                suggestResponse: true,
                                              ),
                                            );
                                          },
                                        ).then((text) {
                                          if (text != null) {
                                            quillEditorController.setText(text);
                                            scrollToRemarks();
                                          }
                                        });
                                      },
                                      text: "Draft with AI",
                                      icon: Icons.drafts_rounded,
                                      color: AppColors.secondary,
                                      padding: const EdgeInsets.symmetric(
                                          horizontal: 16, vertical: 12),
                                    ),
                                  ],
                                ),
                                const SizedBox(height: 12),
                                const Divider(
                                  color: Colors.grey,
                                ),
                                //const SizedBox(height: 12),
                              ],
                            ),
                          // if (details?.attachments != null &&
                          //     details!.attachments.isNotEmpty)
                          //   ReadOnlyFlagAttachmentList(
                          //     header: header(Icons.flag_outlined, "Flags"),
                          //     data: details!.attachments,
                          //   ),
                          if (!viewOnly)
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                const SizedBox(height: 24),
                                if (widget.fileType ==
                                    FileType.actionRequired) ...[
                                  header(Icons.pending_actions, "Action"),
                                  const SizedBox(height: 16),
                                  AppText.bodyMedium(
                                    "Archive File with actions below or Forward to another user if necessary",
                                  ),
                                  const SizedBox(height: 8),
                                  SelectionChips<FileAction>(
                                      chipColor: AppColors.secondaryDark,
                                      menu: FileAction.values
                                          .map((e) => SelectionChipMenuItem(
                                              label: e.label, value: e))
                                          .toList(),
                                      initialSelected:
                                          FileAction.values.indexOf(action),
                                      onSelected: (index, FileAction val) {
                                        attachments.clear();
                                        WidgetsBinding.instance
                                            .addPostFrameCallback((_) async {
                                          allFlags = await controller.getFlags(
                                              onlyFinal:
                                                  val != FileAction.forward);
                                          setState(() {
                                            action = val;
                                          });
                                          initAttachment();
                                        });
                                      }),
                                  const SizedBox(height: 16),
                                ],
                                if (widget.fileType == FileType.pending ||
                                    (widget.fileType ==
                                            FileType.actionRequired &&
                                        action == FileAction.forward) ||
                                    (widget.fileType == FileType.archived &&
                                        reOpenedFile)) ...[
                                  Column(
                                    children: [
                                      header(Icons.work_history_outlined,
                                          "Forward to"),
                                      const SizedBox(height: 16),
                                      AppDropDownField<SectionModel>(
                                        items: state.sections,
                                        onChanged: (item) async {
                                          setState(() {
                                            selectedSection = item;
                                          });
                                          forwardToList = await controller
                                              .getForwardTo(item?.id);
                                          setState(() {
                                            if (forwardToList != null &&
                                                forwardToList?.length == 1) {
                                              forwardTo = forwardToList?.first;
                                            }
                                          });
                                        },
                                        labelText: "Section",
                                        hintText: "Select Section",
                                        prefix: state.loadingSections
                                            ? fieldLoader
                                            : null,
                                        itemBuilder: (item) {
                                          return AppText.titleMedium(
                                              item?.title ?? '');
                                        },
                                        validator: (item) {
                                          if (selectedSection == null ||
                                              item == null) {
                                            return 'Please select a value';
                                          }
                                          return null;
                                        },
                                      ),
                                      const SizedBox(height: 12),
                                      AppDropDownField<ForwardToModel>(
                                        items: forwardToList ?? [],
                                        onChanged: (item) async {
                                          setState(() {
                                            forwardTo = item;
                                          });
                                        },
                                        labelText: "Forward this file to",
                                        hintText: "Forward To",
                                        prefix: state.loadingSections
                                            ? fieldLoader
                                            : null,
                                        buttonHeight:
                                            forwardTo == null ? null : 57,
                                        itemBuilder: (item) {
                                          return Column(
                                            crossAxisAlignment:
                                                CrossAxisAlignment.start,
                                            children: [
                                              AppText.titleMedium(
                                                  item?.userTitle ?? ''),
                                              // In your itemBuilder or wherever you use it:
                                              // Height: ~20px (half of standard)
                                              Container(
                                                padding:
                                                    const EdgeInsets.symmetric(
                                                        horizontal: 6,
                                                        vertical: 1),
                                                decoration: BoxDecoration(
                                                  color: Colors.yellow[400],
                                                  borderRadius:
                                                      BorderRadius.circular(8),
                                                  border: Border.all(
                                                    color: Colors.yellow[600]!
                                                        .withOpacity(0.3),
                                                    width: 0.5,
                                                  ),
                                                ),
                                                child: AppText.labelSmall(
                                                  item?.designationTitle ?? '',
                                                  color: Colors.black,
                                                  fontWeight: FontWeight.w500,
                                                  fontSize: 10, // Smaller font
                                                ),
                                              )
                                            ],
                                          );
                                        },
                                        selectedItemBuilder: (ctx) {
                                          return forwardToList?.map((item) {
                                                return Padding(
                                                  padding:
                                                      const EdgeInsets.all(8.0),
                                                  child: Column(
                                                    crossAxisAlignment:
                                                        CrossAxisAlignment
                                                            .start,
                                                    children: [
                                                      AppText.titleMedium(
                                                          item.userTitle ?? ''),
                                                      AppText.labelLarge(
                                                          item.designationTitle ??
                                                              ''),
                                                    ],
                                                  ),
                                                );
                                              }).toList() ??
                                              [];
                                        },
                                        validator: (item) {
                                          if (forwardTo == null ||
                                              item == null) {
                                            return 'Please select a value';
                                          }
                                          return null;
                                        },
                                      ),
                                      // AppDropDownField<ForwardToModel>(
                                      //   enabled: selectedSection != null &&
                                      //       !state.loadingForwardList,
                                      //   controller: TextEditingController(
                                      //       text:
                                      //           "${forwardTo?.userTitle ?? ''} ${forwardTo?.designationTitle == null ? "" : "(" + forwardTo!.designationTitle! + ")"}"),
                                      //   suggestionsCallback: (_) {
                                      //     return forwardToList ?? [];
                                      //   },
                                      //   onSelected: (item) {
                                      //     setState(() {
                                      //       forwardTo = item;
                                      //     });
                                      //   },
                                      //   labelText: "Forward this file to",
                                      //   hintText: "Forward to",
                                      //   prefix: selectedSection != null &&
                                      //           state.loadingForwardList
                                      //       ? SizedBox(
                                      //           width: 24,
                                      //           height: 24,
                                      //           child: Padding(
                                      //             padding:
                                      //                 const EdgeInsets.symmetric(
                                      //               horizontal: 8.0,
                                      //               vertical: 8,
                                      //             ),
                                      //             child: fieldLoader,
                                      //           ),
                                      //         )
                                      //       : null,
                                      //   itemBuilder: (ctx, item) {
                                      //     return Padding(
                                      //       padding: const EdgeInsets.all(8.0),
                                      //       child: Column(
                                      //         crossAxisAlignment:
                                      //             CrossAxisAlignment.start,
                                      //         children: [
                                      //           AppText.titleMedium(
                                      //               item?.userTitle ?? ''),
                                      //           AppText.labelLarge(
                                      //               item?.designationTitle ?? ''),
                                      //         ],
                                      //       ),
                                      //     );
                                      //   },
                                      //   validator: (item) {
                                      //     if (forwardTo == null || item == null) {
                                      //       return 'Please select a value';
                                      //     }
                                      //     return null;
                                      //   },
                                      // ),
                                    ],
                                  ),
                                ],
                                const SizedBox(height: 8),
                                const Divider(color: Colors.grey),
                                const SizedBox(height: 8),
                                header(
                                    Icons.attach_file, "Flag and Attachment"),
                                const SizedBox(height: 12),
                                ListView.separated(
                                  itemCount: attachments.length,
                                  shrinkWrap: true,
                                  physics: const NeverScrollableScrollPhysics(),
                                  separatorBuilder: (_, i) => Divider(
                                    height: 40,
                                    color: AppColors.secondaryLight
                                        .withOpacity(0.5),
                                  ),
                                  itemBuilder: (ctx, i) {
                                    final model = attachments[i];
                                    return AddFlagAndAttachment(
                                      key: ValueKey(model),
                                      model: model,
                                      onDelete: i == 0
                                          ? null
                                          : () {
                                              setState(() =>
                                                  attachments.removeAt(i));
                                            },
                                    );
                                  },
                                ),
                                const SizedBox(height: 12),
                                Align(
                                  alignment: Alignment.centerRight,
                                  child: AppOutlineButton(
                                    onPressed: () {
                                      setState(() {
                                        if (widget.fileType ==
                                                FileType.actionRequired &&
                                            action != FileAction.forward) {
                                          attachments.add(
                                            FlagAndAttachmentModel(
                                              usedFlags: [],
                                            ),
                                          );
                                        } else {
                                          attachments.add(
                                            FlagAndAttachmentModel(
                                              usedFlags: [
                                                ...flagsUsed,
                                                ...attachments
                                                        .map((e) =>
                                                            e.flagType ??
                                                            FlagModel())
                                                        .toList() ??
                                                    [],
                                              ],
                                            ),
                                          );
                                        }
                                      });
                                    },
                                    text: "Add More",
                                    color: AppColors.secondary,
                                    padding: const EdgeInsets.symmetric(
                                        horizontal: 16, vertical: 12),
                                  ),
                                ),
                                const SizedBox(height: 24),
                                // Align(
                                //   alignment: Alignment.centerLeft,
                                //   child: Column(
                                //     crossAxisAlignment:
                                //         CrossAxisAlignment.start,
                                //     children: [
                                //       AppText.titleLarge(
                                //         "Your File Movement Number is:",
                                //         color: AppColors.secondaryDark,
                                //       ),
                                //       AppText.bodyMedium(
                                //           autoGeneratedFileNumber),
                                //     ],
                                //   ),
                                // ),
                                // const SizedBox(height: 24),
                              ],
                            ),
                          AppSolidButton(
                            onPressed: () async {
                              FocusScope.of(context).unfocus();
                              FocusManager.instance.primaryFocus?.unfocus();

                              if (widget.fileType == FileType.archived) {
                                if (!reOpenedFile) {
                                  reOpenedFile = true;
                                  fetchData();
                                } else {
                                  if (!formKey.currentState!.validate()) return;
                                  if (!allAttachmentsValid) {
                                    Toast.error(
                                        message:
                                            "One or more flags are missing attachments. Add a file and then try again");
                                    return;
                                  }
                                  String text =
                                      await quillEditorController.getText();
                                  if (text.trim().isEmpty) {
                                    Toast.show(
                                        message:
                                            "Add remarks before you submit");
                                    return;
                                  }
                                  String spacedText = text;
                                  controller.reopenFile(
                                    fileId: details!.content.first!.fileId!,
                                    content: spacedText,
                                    forwardTo: forwardTo?.userDesgId,
                                    sectionId: selectedSection?.id,
                                    flags: attachments,
                                  );
                                }
                                return;
                              }

                              if (viewOnly) {
                                RouteHelper.pop();
                                return;
                              }

                              if (!formKey.currentState!.validate()) return;
                              if (!allAttachmentsValid) {
                                Toast.error(
                                    message:
                                        "One or more flags are missing attachments. Add a file and then try again");
                                return;
                              }

                              String text =
                                  await quillEditorController.getText();
                              if (text.trim().isEmpty) {
                                Toast.show(
                                    message: "Add remarks before you submit");
                                return;
                              }

                              String spacedText = text;

                              bool submissionSuccess = false;

                              if (widget.fileType == FileType.pending) {
                                try {
                                  await controller.sendPendingFileRemarks(
                                    fileId: details!.content.first!.fileId!,
                                    content: spacedText,
                                    forwardTo: forwardTo!.userDesgId!,
                                    fileMovNo: autoGeneratedFileNumber,
                                    lastTrackId:
                                        details!.content!.last!.trackId!,
                                    flags: attachments,
                                  );
                                  submissionSuccess = true;
                                } catch (e) {
                                  submissionSuccess = false;
                                  print("Error: $e");
                                  Toast.error(message: "Failed to submit file");
                                }
                              } else if (widget.fileType ==
                                  FileType.actionRequired) {
                                try {
                                  await controller.submitFile(
                                    fileId: details!.content.first!.fileId!,
                                    content: spacedText,
                                    forwardTo: forwardTo?.userDesgId,
                                    fileMovNo: autoGeneratedFileNumber,
                                    action: action,
                                    flags: attachments,
                                  );
                                  submissionSuccess = true;
                                } catch (e) {
                                  submissionSuccess = false;
                                  print("Error: $e");
                                  Toast.error(message: "Failed to submit file");
                                }
                              }

                              if (submissionSuccess && mounted) {
                                try {
                                  final dashboardNotifier =
                                      ref.read(dashboardController.notifier);

                                  await dashboardNotifier.initData();
                                  await dashboardNotifier.fetchPendingFiles();

                                  Toast.show(
                                      message: "File submitted successfully");

                                  if (mounted) {
                                    RouteHelper.pop();
                                  }
                                } catch (e) {
                                  print("Error: $e");
                                  if (mounted) {
                                    RouteHelper.pop();
                                  }
                                }
                              }
                            },
                            text: isUnopenedArchived
                                ? "Reopen"
                                : viewOnly
                                    ? "Close"
                                    : "Send File",
                            backgroundColor: AppColors.primary,
                            width: double.infinity,
                          ),
                          const SizedBox(height: 16),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
      ),
    );
  }

  Widget header(IconData icon, String title) {
    return Row(
      children: [
        Card(
          margin: const EdgeInsets.all(0),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
          color: AppColors.cardColor,
          child: Padding(
            padding: const EdgeInsets.all(6.0),
            child: Icon(icon, size: 20, color: AppColors.primaryDark),
          ),
        ),
        const SizedBox(width: 8),
        AppText.titleMedium(
          title,
          color: AppColors.primaryDark,
          fontWeight: FontWeight.w600,
        ),
      ],
    );
  }

  final Widget fieldLoader = Container(
    width: 12,
    height: 12,
    margin: const EdgeInsets.only(right: 8),
    child: const CircularProgressIndicator(
      strokeWidth: 2,
    ),
  );
}
