// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUlHfcpST99HHT07rTgVUACDNu7ahOTyk',
    appId: '1:497476277328:web:934aed2a67e4836dda2d55',
    messagingSenderId: '497476277328',
    projectId: 'cmdu-482e5',
    authDomain: 'cmdu-482e5.firebaseapp.com',
    storageBucket: 'cmdu-482e5.firebasestorage.app',
    measurementId: 'G-C87T9WZ073',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR9aLmhu9o7QV501XAzorLG3eKJlAO7sM',
    appId: '1:497476277328:android:0e9ed30531c5ec10da2d55',
    messagingSenderId: '497476277328',
    projectId: 'cmdu-482e5',
    storageBucket: 'cmdu-482e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpqdDBov7TRjoDULaGJ_Rrjlog5Ov0WI8',
    appId: '1:497476277328:ios:d96b54f1c17249e0da2d55',
    messagingSenderId: '497476277328',
    projectId: 'cmdu-482e5',
    storageBucket: 'cmdu-482e5.firebasestorage.app',
    iosBundleId: 'com.lrm.efilingBalochistan',
  );
}
